version: 2.1

defaults: &defaults
  docker:
    - image: cimg/node:16.19.0-browsers
  working_directory: ~/glorious-taslonic

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: "."
          paths:
            - "*"

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: "."
          paths:
            - "*"

  format:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Format
          command: npm run format

  test_react:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Test React
          command: |
            npm run test -w=packages/react -- --runInBand --coverage --coverageReporters=lcov
      - persist_to_workspace:
          root: "."
          paths:
            - "./packages/react/coverage/lcov.info"

  test_vue:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Test Vue
          command: |
            npm run test -w=packages/vue -- --runInBand --coverage --coverageReporters=lcov
      - persist_to_workspace:
          root: "."
          paths:
            - "./packages/vue/coverage/lcov.info"

  test_coverage_upload:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Install Coveralls CLI
          command: curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin
      - run:
          name: Upload Coverage Reports
          command: |
            coveralls --repo-token=$COVERALLS_REPO_TOKEN -f packages/vue/coverage/lcov.info --base-path packages/vue/ --parallel --job-flag vue && \
            coveralls --repo-token=$COVERALLS_REPO_TOKEN -f packages/react/coverage/lcov.info --base-path packages/react/ --parallel --job-flag react && \
            coveralls --done


  docs:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Docs
          command: NODE_ENV=production npm run docs
      - persist_to_workspace:
          root: "."
          paths:
            - "*"

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/glorious-taslonic
      - run:
          name: Deploy
          command: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2

  branch-workflow:
    jobs:
      - install
      - build:
          requires:
            - install
      - docs:
          requires:
            - install
            - build
      - format:
          requires:
            - install
      - test_react:
          requires:
            - install
      - test_vue:
          requires:
            - install
      - test_coverage_upload:
          requires:
            - test_react
            - test_vue
      - deploy:
          requires:
            - build
            - docs
            - format
            - test_react
            - test_vue
          filters:
            branches:
              only:
                - master
